language: node_js
node_js:
- '5.1'
notifications:
  slack:
    secure: F5C36kAtfo0X4upvC0IkRDycsh7vSuRJrPSUm95j7w5LPVClqrIM6Lr4Zn4RkvptGnGTZNGSdPHtNz07bI5LosCjzvkJRpJkOHkPMqM0VydIr1hfIcWnrs9koHtMOMpn2NM1OLgoef5ettRDVDBO6DZFkHhdk2+vlgmCxOK0LcQJ6dMVfG99dhhoewlfCd1OG6yk1U+hW+BMlEwuAxUUxazKfR9NI+KOwxXEmtAM9lTI6nXh83XEbrVSzOlMFz2gPQzZxOLBo7zagPo49q150obG16hI0yvgkw/yH4Fv7Oh/TCedFctrwVp+zwmtJZckxCQ3UxgbV89ZYfK2Fy7RbzPIk3CjsP5w0LtULn5pURyCDiwCkQ0YJYlIDo8bUWGKOwnjUcU2cy2k4GKnNkP4obTzvK3RXWBnVEq57rMh1A6Dwvzu1xImA27+cj0Jx1CjgdoWYw1qQeQ7k/EV4q/vBhvVhIYm4oK7tYMNMevPdfGWmcaJjgT5ZVQ+5xvGhvtI9IJqXfLb9ab+ZiJw2esY9YuDEYZcYiMcFnN3P0SM2syNhfUDrInSx8SrID6ldixS9Ohfiq8KlxINAxm+MlfjL/N9CP4IMTqcUmdcXBOY+sBah3XSbLxlfjGLmrpvSt7/QQGS36AM7/edbe9MtqNkvz1ipQurtn9z0kUMyH4p7Ek=
  on_success: never
  on_failure: always
  on_start: never
